[package]
name = "base"
description = "Fitsme shared code base"
version = "0.1.0"
authors = ["Simon Prykhodko <semion.ababo@gmail.com>"]
edition = "2018"

[dependencies]
glam = "0.15.2"
flate2 = "1.0"
prost = "0.7"
structopt = "0.3"

[build-dependencies]
prost-build = { version = "0.7" }
