[package]
name = "base"
description = "Fitsme shared code base"
version = "0.1.0"
authors = ["Simon Prykhodko <semion.ababo@gmail.com>"]
edition = "2018"

[dependencies]
brotli = "3.3.0"
prost = "0.7"

[build-dependencies]
prost-build = { version = "0.7" }
