[package]
name = "composer"
description = "Fitsme model composer"
version = "0.1.0"
authors = ["Simon Prykhodko <semion.ababo@gmail.com>"]
edition = "2018"

[dependencies]
base = { path = "../base" }
structopt = "0.3"

[dev-dependencies]
float-cmp = "0.8.0"
